### ISSUE TITLE
Global CSS issue with Next.js

### ISSUE THREAD

**Issue by adnansadar** [TuckerMassad/react-animated-counter#15]
@TuckerMassad
Hi, I liked your project demo and wanted to use your package in my Next.js 14.2.3 project. Unfortunately, I'm facing issues running it.
I've posted an image of the issue on compiling my code and below that I have attached a link to the Next.js docs fix suggestion.
I would really appreciate it if you could look into this. 

![image](https://github.com/user-attachments/assets/7d916c10-9f17-4e72-8c26-51916cc43709)

Next.js docs suggestion: [Link](https://nextjs.org/docs/messages/css-npm)

**Comment by TuckerMassad** [comment]
Hi @adnansadar! Can you confirm what version of `react-animated-counter` are you currently using? Are you using `1.7.9` and still running into this issue? Happy to get this resolved for you 😄

**Comment by adnansadar** [comment]
Yes, I am using version 1.7.9

**Comment by TuckerMassad** [comment]
Here is a playground nextjs 14.2 environment and I'm not running into the issue https://codesandbox.io/p/devbox/blissful-wildflower-shdyjj?file=%2Fapp%2Fpage.tsx%3A20%2C19&workspaceId=292bc98c-46dc-4e99-b7ae-fb59ee623eb8. Want to provide me with your code/the file you are importing AnimatedCounter so I can try and help further debug? @adnansadar

**Comment by adnansadar** [comment]
For some reason, I am unable to view the code sandbox

![image](https://github.com/user-attachments/assets/de278449-df21-417e-89f4-9f82b3dda0a7)

**Comment by TuckerMassad** [comment]
My apologies, here is a live sandbox link (you must have a Codesandbox account as well) - https://codesandbox.io/p/live/5bcf9108-8509-415c-801e-d9181ce00ad9 @adnansadar

**Comment by TuckerMassad** [comment]
Let me know if you are still running into this issue or if I can close this one out 😄  @adnansadar

**Comment by TuckerMassad** [comment]
Closing this one out due to inactivity 👍

**Comment by k2xl** [comment]
Hi I'm seeing this same issue
