### ISSUE TITLE
Source mapping

### ISSUE THREAD

**Issue by Amyel09** [TuckerMassad/react-animated-counter#4]
![image](https://github.com/TuckerMassad/react-animated-counter/assets/107402747/d478cc1f-f7d9-4ece-bef0-d8da0b28a096)

**Comment by Amyel09** [comment]
What's going on?

**Comment by Amyel09** [comment]
It does not affect the use, but reports this warning

**Comment by TuckerMassad** [comment]
Thanks for the report! @Amyel09 I'll look into this and check back here when I resolve the warning from reporting

**Comment by TuckerMassad** [comment]
Hi @Amyel09. I've resolved the source map warning issue, if you can please bump your package version to `1.7.0` and confirm that you are no longer seeing the warnings I'll go ahead and close out the ticket. I appreciate you bringing this to light!

**Comment by Amyel09** [comment]
Thank you very much, there are no problems at the moment! @TuckerMassad

**Comment by TuckerMassad** [comment]
Wonderful. If you run into any problems/have any feature requests in the future, feel free to reach out & happy coding! @Amyel09 Closing this issue out 😄
