### ISSUE TITLE
More text customisation options

### ISSUE THREAD

**Issue by Codemaine** [TuckerMassad/react-animated-counter#5]
We should have more customisation options like line-height, font-family, ex.

**Comment by TuckerMassad** [comment]
Hi @Codemaine, thanks for the feature request! Are you currently running into any issues applying a font-family to the component via applying styles in the parent component that is leveraging the `<AnimatedCounter>`? If you take a peak at the example codesandbox in the docs, you can see an example of a custom font being applied (in this case `Comfortaa`). Please let me know if you have any questions :)

**Comment by fordelord** [comment]
Yea, maybe can add some opportunities to change text: convert to localeString or something like that. What do you think about this idea?

**Comment by Codemaine** [comment]
> Hi @Codemaine, thanks for the feature request! Are you currently running into any issues applying a font-family to the component via applying styles in the parent component that is leveraging the `<AnimatedCounter>`? If you take a peek at the example codesandbox in the docs, you can see an example of a custom font being applied (in this case `Comfortaa`). Please let me know if you have any questions :) 

The spacing between the characters is a lot, and I haven't found a way to decrease it

**Comment by TuckerMassad** [comment]
I definitely love the idea/am in favor of spending some time adding more customization options for folks. In terms of the localeString use-case, can you provide me with an example of what you would like to accomplish and/or more detail about the pain-point you are running into? @fordelord 

In terms of the spacing between characters, what font family are you using while running into this issue so I can better replicate the issue? @Codemaine 

Looking forward to adding these features for y'all and hope you're both having a happy new year

**Comment by Codemaine** [comment]
I would love it if you could offer the option for a className for the text, and the font I'm using is Gellix. Happy new year to you too :)

**Comment by fordelord** [comment]
@TuckerMassad Yea, I have the component which show the estimated yearnings of the user and this number looks really big. To make number more readable I add the LocaleString to add coma between 3 number like: 123,456.78 ; 12,231.00; 12,231; 492,392,342.48. This style make number more readable and understandable from this 123456.00 to this -> 123,456.00. Can you add this feature to your library? I think this feature will make this library more customizable and comfortable.

**Comment by TuckerMassad** [comment]
Hey folks @Codemaine @fordelord. I've added some modifications to ensure uniformity of spacing of each individual integer as well as a new optional `formatLocale` boolean prop that applies [Number.toLocaleString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) if it is set to `true` (this adds commas for `en-US` users for example). If you bump your package version up to `1.7.5` you can give it a whirl. Below is a demo codesandbox link as well if you want to give it a whirl. Let me know if y'all have any additional requests and/or suggestions!

![updatedcounter](https://github.com/TuckerMassad/react-animated-counter/assets/22939424/be87b797-77de-42c9-8b3a-fa9661205d0e)


https://codesandbox.io/p/sandbox/floral-glitter-h6wzpp?file=%2Fsrc%2FApp.js

**Comment by fordelord** [comment]
@TuckerMassad Thank you for your work, but it doesn't work properly, I have tested it and you can see the bug in the demo: `https://www.loom.com/share/85c565a92ab74912a022b9d6d8c56a1b`

**Comment by fordelord** [comment]
Can you tell me pls when you can fix this?

**Comment by TuckerMassad** [comment]
I appreciate the bug demo! @fordelord  It seems that non `en-US` locales are running into formats that you aren't particularly looking for. If you bump your package version to `1.7.6` and replace the `formatLocale` boolean with `includeCommas` you should see your problem fixed. Ex.

```
<AnimatedCounter
  value={counterValue}
  color="white"
  fontSize="60px"
  includeCommas={true}
/>
```

Another codesandbox for you to give it a try: https://codesandbox.io/p/sandbox/dank-night-x4syjs?file=%2Fsrc%2FApp.js%3A25%2C41

**Comment by TuckerMassad** [comment]
Closing this one out as I haven't seen additional activity here + added requested functionality via the `includeCommas` prop. Please feel free to open additional feature requests in the future and i'll be sure to take a look at em 😄
