### ISSUE TITLE
bug: negative number displays as 0

### ISSUE THREAD

**Issue by mercer08** [TuckerMassad/react-animated-counter#7]
i have bug report, negative number displays as 0, is there any soluation for this?

**Comment by TuckerMassad** [comment]
Hi @mercer08. Great find - I'll definitely have this addressed within the next couple of days. I'll keep this issue thread once the package has been updated.

**Comment by TuckerMassad** [comment]
Hi @mercer08. If you would kindly bump your package version to `1.7.7` the issue should now be resolved. Please let me know if things are working as expected and/or you see any other issues in the meantime! 😄

**Comment by TuckerMassad** [comment]
Closing this out as the issue is resolved + no further comments on it 👍
