### ISSUE TITLE
Spacing issue on most fonts

### ISSUE THREAD

**Issue by mikiyasET** [TuckerMassad/react-animated-counter#8]
![telegram-cloud-photo-size-4-5958702202312834821-y](https://github.com/TuckerMassad/react-animated-counter/assets/25723129/1acae481-7b5e-43d5-9940-33d537f99b53)
![telegram-cloud-photo-size-4-5958702202312834822-y](https://github.com/TuckerMassad/react-animated-counter/assets/25723129/5eac8c81-c7af-47fd-9950-8244d063e52d)

There is a gap as you see I changed the alignment of .ticker-digit to center on the image above but still got a slight gap before the comma, I think the placeholder which is 0 is causing this problem since 0 has a larger width in most fonts the font on the image is [Inter](https://fonts.google.com/specimen/Inter?query=inter)

**Comment by TuckerMassad** [comment]
Hey @mikiyasET. Thanks for bringing this up! I agree the comma after the one is a _bit_ of an eye-sore. I'll work on a fix for this and run some proposals by you in this issue thread 👍

**Comment by TuckerMassad** [comment]
One note for you in the meantime @mikiyasET, if you are overriding styles in the `.ticker-digit` class you may want to try using the [font-feature-settings: "tnum"](https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings) style declaration in your stylesheet for `.ticker-digit`. This ensures all numbers have "equal" spacing and could resolve your issue in the interim.

Heres a related tweet I found interesting thats related to animated numbers like this component https://x.com/jh3yy/status/1715409590320288041?s=20

**Comment by TuckerMassad** [comment]
Made some adjustments to the spacing of the decimal point/commas, if you don't mind bumping your package version to `1.7.8` and giving it a whirl 😄 @mikiyasET

**Comment by mikiyasET** [comment]
Have you teated it on the font I specified

**Comment by TuckerMassad** [comment]
Wonderful 😄 Going to close this one out but if anything pops up in the future feel free to open another issue! @mikiyasET
